Repository TobiAjila/openj9, pull requests merged in 2019-06, with the labels that each got.

#11 Updated JVMImage Read/Write
  runtime/oti/jvmimage.h
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
  runtime/vm/j9vm.tdf
Labels: extension

#9 Registering Structure and Class Loader Allocation
  runtime/cfdumper/CMakeLists.txt
  runtime/cfdumper/module.xml
  runtime/oti/jvmimage.h
  runtime/oti/jvmimage_api.h
  runtime/tests/vm/CMakeLists.txt
  runtime/tests/vm/module.xml
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
  runtime/vm/KeyHashTable.c
  runtime/vm/ModularityHashTables.c
  runtime/vm/classallocation.c
  runtime/vm/j9vm.tdf
  runtime/vm/jvminit.c
Labels: feature, first Issue

#12 Updated Read/Write & Code Standard
  runtime/oti/jvmimage.h
  runtime/oti/jvmimage_api.h
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
  runtime/vm/jvminit.c
Labels: bug

#13 Deregistering and Shrinking Table
  runtime/oti/jvmimage_api.h
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
  runtime/vm/classallocation.c
  runtime/vm/j9vm.tdf
Labels: extension

#16 Place JVMImage instance into JVMImagePortLibrary
  runtime/oti/j9nonbuilder.h
  runtime/oti/jvmimage.h
  runtime/oti/jvmimage_api.h
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
  runtime/vm/KeyHashTable.c
  runtime/vm/ModularityHashTables.c
  runtime/vm/classallocation.c
  runtime/vm/j9vm.tdf
  runtime/vm/jvminit.c
Labels: bug, extension

#17 Akshayben/restructure image port
  runtime/oti/jvmimage.h
  runtime/oti/jvmimage_api.h
  runtime/oti/jvmimageport.h
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
  runtime/vm/KeyHashTable.c
  runtime/vm/ModularityHashTables.c
  runtime/vm/jvminit.c
Labels: extension

#21 Added class path entries
  runtime/util/cphelp.c
Labels: extension

#20 JVM Image Fixes
  runtime/oti/jvmimage.h
  runtime/vm/JVMImage.cpp
Labels: bug, extension

#19 allocate memory in segment.c
  runtime/oti/jvmimageport.h
  runtime/vm/JVMImage.cpp
  runtime/vm/segment.c
Labels: extension

#23 Register Class into Table (#19)
  runtime/oti/j9nonbuilder.h
  runtime/oti/jvmimage.h
  runtime/oti/jvmimage_api.h
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
  runtime/vm/createramclass.cpp
  runtime/vm/intfunc.c
Labels: extension
