Repository TobiAjila/openj9, pull requests merged in 2019-07, with the labels that each got.

#24 Made jvmImageHeader aligned to Page Size
  runtime/oti/jvmimage.h
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
Labels: bug

#25 JVMImage Shutdown Behaviour is now Implemented
  runtime/oti/jvmimage_api.h
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
  runtime/vm/jvminit.c
Labels: bug, feature

#26 Classloader and Class fixup
  runtime/cfdumper/CMakeLists.txt
  runtime/cfdumper/module.xml
  runtime/jcl/common/stdinit.c
  runtime/oti/j9nonbuilder.h
  runtime/oti/jvmimage.h
  runtime/oti/jvmimage_api.h
  runtime/tests/vm/CMakeLists.txt
  runtime/tests/vm/module.xml
  runtime/vm/CMakeLists.txt
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
  runtime/vm/classallocation.c
  runtime/vm/intfunc.c
  runtime/vm/jvmimagetable.c
  runtime/vm/jvminit.c
Labels: feature, first Issue

#22 added register class path entries
  runtime/util/cphelp.c
Labels: extension

#27 Segment Allocation in list
  runtime/vm/jvminit.c
  runtime/vm/segment.c
Labels: bug

#28 Added class path entry allocation.
  runtime/vm/jvmfree.c
  runtime/vm/jvminit.c
Labels: bug

#29 Registering Class Path Entries For fixup
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
  runtime/vm/jvminit.c
Labels: bug, feature

#30 Fixed up the last iTable for each class
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
Labels: bug

#31 Fixed Teardown sequence.
  runtime/jcl/common/stdinit.c
  runtime/oti/j9nonbuilder.h
  runtime/oti/jvmimage_api.h
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
  runtime/vm/intfunc.c
  runtime/vm/segment.c
Labels: bug, extension

#33 Fix Object References:
  runtime/jcl/common/jcldefine.c
  runtime/oti/j9nonbuilder.h
  runtime/oti/jvmimage_api.h
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
  runtime/vm/classsupport.c
  runtime/vm/intfunc.c
Labels: bug

#34 Tag cleanup
  runtime/oti/jvminit.h
  runtime/vm/JVMImage.cpp
  runtime/vm/JVMImage.hpp
  runtime/vm/jvminit.c
Labels: extension
